### ISSUE TITLE
Documentation for editable filenames

### ISSUE THREAD

**Issue by Sixl-Daniel** [safrazik/vue-file-agent#101]
I have a very hard time figuring out how to use the editable filenames.

In the docs it is mentioned that the modified name can be retrieved by "fileRecord.name" which did not really help. I can find the new custom name for a file in a property called _"customName"_ in **$refs.vueFileAgent.fileRecords**, but it is unclear how to rename the uploaded file object. 

Is there an example implementation somewhere? Thank you for an awesome upload solution.

**Comment by safrazik** [comment]
Yes you can retrieve with `fileRecord.name()` as mentioned [in the docs](https://safrazik.com/vue-file-agent/docs/#editable)
please NOTE the parenthesis in `.name()`

If you want to get the new name as soon as renamed, please use the `rename` event (I forgot to document it, unfortunately)
But the implementation is already there:

https://github.com/safrazik/vue-file-agent/blob/7f7c931b51c8724c852be60a824cac7235c1dad3/src/components/vue-file-agent-mixin.ts#L480

```html
<VueFileAgent
  @rename="fileRenamed($event)"
></VueFileAgent>
```
```javascript
export default {
  methods: {
    fileRenamed(fileRecord) {
      const withoutExtension = true
      console.log('New name', fileRecord.name(withoutExtension))
    }
  }
}
```

---
will close this issue as soon as the `rename` event documentation is added

**Comment by safrazik** [comment]
As a side note, `v2` will have a different and expressive/meaningful api for getting and setting these type of data (name, error, progress, etc.)
