### ISSUE TITLE
Allow suppling thumbnails

### ISSUE THREAD

**Issue by hallekamp** [safrazik/vue-file-agent#106]
It is impossible to supply thumbnails on initialization. My backend generates thumbnails and i would like to use them. 
The proposed change would also end the calls to my s3 bucket where the 1-20 megabytes large files are hosted and that are download every time the file component is initialized.

**Describe the solution you'd like**
I thought it would be the simplest solution would be to allow setting urlResized explicitly.
````
{
  "name":"11867277_6.jpg",
  "lastModified":"2020-10-27T21:50:40+01:00",
  "sizeText":"49.1 KB",
  "size":50277,
  "type":"image/jpeg",
  "ext":"jpg",
  "url":"https://temporary-path-to-s3-bucket/11867277_6.jpg",
  "urlResized":"https://storage-on-application-server/11867277_6-thumb.jpg"
}
````

For that two changes to file-record are needed:
````
// line 75
const promise = fileRecord.setUrl(rawFileRecord.url as string, rawFileRecord.urlResized as string);
````

````
// line 326
public setUrl(url: string | null, urlResized: string | null): Promise<this> {
    this.urlValue = url;
    return new Promise((resolve, reject) => {
      if(urlResized){
        this.urlResized = urlResized;
      } else
      if (this.isImage()) {
        ...
      }
      resolve(this);
    });
  }
````

**Comment by safrazik** [comment]
Will be considered for the next update.
Related: #66

**Comment by safrazik** [comment]
Duplicate #66
