### ISSUE TITLE
Do you have a sample for S3 JS upload

### ISSUE THREAD

**Issue by Kendysond** [safrazik/vue-file-agent#107]
Hi, 

Congrats on the plugin, it looks amazing. Does it support S3 upload where the uRL is signed first, before it's uploaded to the S3 bucket?

**Comment by safrazik** [comment]
@hallekamp can you please help @Kendysond others with an example based on your implementation with S3? It will help many people since S3 is used widely. Thanks.

**Comment by hallekamp** [comment]
@Kendysond i do use this with s3 storage, but i have build a backend in laravel that handles s3 up-/download.
I basicly just implemented the php upload example in a laravel conform fashion in conjunction with spatie/media-library
````
    public function handleUpload($request, $model)
    {
        $media = $model
            ->addMediaFromRequest('file')
            ->storingConversionsOnDisk('public') // save thumbnails on the application server
            ->toMediaCollection('media', 's3');

        return [
            self::UPLOAD_KEY => $media->id,
        ];
    }
````
You could adapt one of examples as a base and insert the signing right before the data is pushed to the bucket.

**Comment by Kendysond** [comment]
Thanks @safrazik @hallekamp , yeah, I'll try to implement the signing version and share the code if I'm able to make it work. Thanks again.

**Comment by Kendysond** [comment]
Got the presigned S3 upload to work. I'd try to share a cleaned up sample ASAP.

**Comment by alexcroox** [comment]
@Kendysond do you have a simple example with signed url usage? It’s a 2 step upload process for each file so it would be interesting to see how this component can handle that.

**Comment by Kendysond** [comment]
@alexcroox , yeah, happy to share what I have. 

` <vue-file-agent ref="fileUpload"
 @upload="onUpload($event)"
                         @select="filesSelected($event)" .....
`
```
async filesSelected(fileRecordsNewlySelected) {
            
            var validFileRecords = fileRecordsNewlySelected.filter((fileRecord) => !fileRecord.error);
            
                for (let index = 0; index < validFileRecords.length; index++) {
                    const validFile = validFileRecords[index];
                    const fileName = validFile.name()

                    const { data } = await axios.post(this.$route('getAWSFileSignature'), { filename: fileName, filetype: 'download' }); // this calls the backend to get the presigned upload details
                    validFile.appendData = data
                }
             
                this.$refs.fileUpload.upload(this.$page.s3_bucket_url, {}, validFileRecords, function createFormData(fileData){
                   //this passes all the presigned url key and values as post params and posts it to the S3 url along with the file object. 
                    var formData = new FormData();
                    let appendData = fileData.raw.appendData
                    delete appendData.success;
                    for (var field in appendData) {
                        formData.append(field, appendData[field]);
                    }
                    formData.append('file',  fileData.file);
                    return formData;
                });
```

If it helps, my presigned api request response looks like this:
```
{
    "success": true,
    "AWSAccessKeyId": "AKIxxxxxxxxx",
    "key": "xxxx/xxxx/french-made-easy-course-f-selar-co-5fee314383ac6-20210102051256.jpeg",
    "success_action_status": 200,
    "policy": "eyAiZXhwxxxxxxxxxxxxx",
    "Content-type": "application\/octet-stream",
    "acl": "public",
    "signature": "FZamAFxxxxxxxx"
}
```
PS: Because I'm using the internal vue-file-agent upload function `this.$refs.fileUpload.upload`, once the upload to s3 is done, I was able to hook into the event with the `onUpload` event handler to get the uploaded file details and store that somewhere. 

I hope this helps. So far this seems to work smoothly, but I'm curious to try multipart uploads, not even sure how to pull that off.
