### ISSUE TITLE
Vue 3 Support

### ISSUE THREAD

**Issue by nunonux** [safrazik/vue-file-agent#113]
Hello!

Do you have any idea to do with support for Vue 3?
Tks!

**Comment by coldluca** [comment]
Hi, any updates on this topic?

Thank you

**Comment by safrazik** [comment]
No plans to support Vue 3 in `v1` yet but File Agent `v2` will have support for Vue 3 out of the box.

**Comment by jeffersonagostinho** [comment]
Hello guys!

Very nice component! 

Any predictions for the v2 release for vue 3 support?

**Comment by masterkain** [comment]
any news? 😊

**Comment by tiagocarvalhomk** [comment]
Hello

Any news?

**Comment by barisener** [comment]
@safrazik any update about v2 👀

**Comment by johnwc** [comment]
@safrazik @kohenkatz @seriouslag @kevinleedrum 
Is there anyone on this project anymore, is it considered abandoned?

**Comment by trikarai** [comment]
guys.. 
the owner is from sri lanka, and sri lanka is in a brick of collapse... don't expect to much.

**Comment by safrazik** [comment]
Hey guys. Vue 3 is not supported for this library. Apologies

**Comment by barisener** [comment]
😢

**Comment by boindil** [comment]
@safrazik are you still working on this project (thus making a v2) or did you give up on this?

**Comment by boindil** [comment]
As mentioned in #198 I started working on a Vue3 compatible version. I will be only be fixing bugs though and new features are not planned.

Whilst I will not be adding any new features on my own, any feature or improvement PRs are welcome.

https://github.com/boindil/vue-file-agent-next / https://www.npmjs.com/package/@boindil/vue-file-agent-next
