### ISSUE TITLE
How this package used in Vue3.0 Version?

### ISSUE THREAD

**Issue by ravshrikantsoni** [safrazik/vue-file-agent#116]
I'm able to use this package in vue version 2.0 but how it can use in to Vue3.0 version. Its giving error Uncaught TypeError: Cannot read property 'extend' of undefined.

**Comment by benoitLecuppe** [comment]
i've the same problem

**Comment by safrazik** [comment]
No plans to support Vue 3 in `v1` yet but File Agent `v2` will have support for Vue 3 out of the box.

**Comment by safrazik** [comment]
Duplicate #113
