### ISSUE TITLE
Upload Multiple Queued Files Serially, Instead Of Parallelly

### ISSUE THREAD

**Issue by jwbats** [safrazik/vue-file-agent#118]
**Problem**

Currently, I'm facing a problem where multiple image uploads to my server are causing many uploads to fail. The exception that is thrown is that MsSQL has selected deadlock victims.

This happens with as little as 3 parallel image uploads.

I used to use Dropzone, which allowed for uploading multiple files serially, rather than parallelly. This never caused problems.

**Suggested Solution**

If vue-file-agent would support a setting for serial uploading, I'm sure that would solve my problem.

Ofcourse, I could modify the way things work on the server side in order to prevent deadlocks from occurring so quickly in the first place. But it's always possible for a user to encounter a situation where he wants to go easy on his server resources.

Serial uploads are an easy way of achieving this.

It would also help if the upload event was fired for every serial upload, so that the screen can be updated with successful uploads in real time.

**My Use Case**

I'm building a screen where images need to be uploaded. The typical number of uploads is 10-20. It wouldn't occur to me to let regular visitors of my site upload that many images all at once, but this screen is for admins (such as myself).

It's user friendly if I can let admins drag 10-20 images into the upload box. But since admins will only be doing this a few times per week, it's okay if not everything goes at once. Especially since some CPU intensive image processing is done on the server side.

**Comment by safrazik** [comment]
Will consider adding serial support in the future. But you can do it already with a wrapper function. Example (based on “Advanced Demo”):
(Assuming you’re working in an environment with `async`, `await` support)

```javascript
    methods: {
      async uploadFilesSerially(fileRecords) {
        for(const fileRecord of fileRecords) {
          try {
            // Using the default uploader. You may use another uploader instead.
            cont result = await this.$refs.vueFileAgent.upload(this.uploadUrl, this.uploadHeaders, [fileRecord]);
          } catch(error) {
            // handle error
          }
        }
      },
      uploadFiles: function () {
        this.uploadFilesSerially(this.fileRecordsForUpload);
        this.fileRecordsForUpload = [];
      },
    },
```

**Comment by jwbats** [comment]
This solution works very well for me.

I'm now passing along a boolean prop 'serially', based on which I will either call the serial/parallel upload function.

I get better performance from serial uploading than from parallel uploading in my use case. So it would be nice if this would be supported in the future.

For now, my problem is solved, though.

Thanks!

**Comment by jwbats** [comment]
I ran into the problem of [some of my users having errors](https://stackoverflow.com/questions/65761905/error-regeneratorruntime-is-not-defined-for-async-js-functions-in-modern-chro) on the page because of the async function provided above.

As a workaround, I came up with the following promise-rewritten way of serially processing file uploads:

```
// do stuff before uploading files serially
this.beginUpload();

// serially upload files
var promiseChain = this.fileRecords.reduce((accumulator, fileRecord) => {
	return accumulator.then(() => {
		return this.uploadSingleFile(fileRecord);
	});
}, Promise.resolve());

// fires after serial execution of promise chain
promiseChain.then(() => {
	// do stuff after uploading files serially
	this.endUpload();				
});
```

I thought I'd leave it here for anybody who runs into the same problem.

**Comment by safrazik** [comment]
Closing as resolved
