### ISSUE TITLE
Uncaught TypeError: Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by AdrianGrochowski** [safrazik/vue-file-agent#120]
Using cdn I get the error in console : 
vue-file-icon.vue?22fe:13 Uncaught TypeError: Cannot read property 'extend' of undefined
    at Module.fb15 (vue-file-icon.vue?22fe:13)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
    at webpackUniversalModuleDefinition (universalModuleDefinition:9)
    at universalModuleDefinition:10

**Comment by Arash-sad** [comment]
hey @AdrianGrochowski, I have the same issue, how did you resolve this issue?

**Comment by barisener** [comment]
how did you resolve this issue @AdrianGrochowski ? same problem i have 😢
