### ISSUE TITLE
File upload progress with Django vs Other

### ISSUE THREAD

**Issue by dyerrington** [safrazik/vue-file-agent#126]
I've been experimenting using this component on a project and seems to work great considering how fast I was able to get a basic implementation working based on the docs and all the great examples.  I've noticed that when using this with Django in development mode, the UI doesn't render the progress bar at all.  If I change the URL to anything that gives a 404 error, the progress bar appears (with a network error).

Using the latest stable version of Django:
![2021-02-22 20 44 39](https://user-images.githubusercontent.com/2257834/108803555-d61ca600-754f-11eb-8a66-55265fb53d20.gif)

Almost identical implementation from the Codepen:
![2021-02-22 20 47 04](https://user-images.githubusercontent.com/2257834/108803586-e6348580-754f-11eb-9e9d-b99dd5e241e8.gif)

Here's my markup:
```html
    <VueFileAgent
      class="upload-block"
      ref="vfaDemoRef"
      :uploadUrl="'{% url 'testmodule:upload-document' doc_id %}'"
      :uploadHeaders="{'X-CSRFToken': '{{csrf_token}}'}"
      :accept="'image/*,.pdf'"
      :multiple="true"
      :deletable="false"
      :theme="'list'"
      :maxSize="'15MB'"
      :thumbnailSize="120"
      :helpText="'Choose PDF files or drag & drop here.'"
      :errorText="{
        type: 'Please select images or pdf files',
        size: 'Max filesize is 15M!',
      }"
      v-model="fileRecords"
    >
    </VueFileAgent>
```

The component is just defining the data for `fileRecords` so it's not very sophisticated beyond defaults in this example.  Is it something with my backend service?  Does it need to push a specific header back to the client to get the total size transferred or something with a protocol?  I am using Django in development mode so it's not a full-on web server with a complete protocol implemented.  The weird thing is, if I change `uploadUrl` to an invalid route, it does show up. 

Thanks in advance!

**Comment by dyerrington** [comment]
Anyone?

**Comment by dandavison** [comment]
It looks to me like the progress bar is there, just moving very fast! What about if you put a sleep statement in your server-side HTTP handler function -- do you see the progress bar then?

**Comment by safrazik** [comment]
As @dandavison said, I see the progress bar moving fast. The green dot indicates that the whole request is in `done` or `completed` state - i.e: the server responded with a success response.

This (upload speed) could be very common in localhost environments. You can try with a very large file or with sleep/delay in server code as suggested before.

Progress bar notation: 
Yellow bar: uploading (Progress less than 99.9999%) - no response from server yet
Green bar: uploaded (Progress greater than 99.9999%) - no response from server yet
Green dot: uploaded 100% and server responded with success
