### ISSUE TITLE
Submit along with the form, no ajax.

### ISSUE THREAD

**Issue by dhcmega** [safrazik/vue-file-agent#130]
**Is your feature request related to a problem? Please describe.**
I cannot find a full featured package that doesn't upload the files it self. I need them to be added to a form.

**Describe the solution you'd like**
The solution would be to just add it to the form and not upload them.

**Describe alternatives you've considered**
I tried to upload the files to a temporary folder and the create a link to them and add it the form and then retake de files. But there are plenty of cases where the form is not actually submited/finished. I end up with files not being used, etc. Trying to handle and compensate for a situation that is not convinient in this case.
This is for notifications, reports, etc on my system. None of them exist at the server until the form is submited and created.

**Additional context**
I would love to use this package because of the look and feel and being vue friendly, etc.
Also I have seen a issue in which this is also asked and the proposed solution eliminates the drag and drop feature.

Thanks!

**Comment by jrtitus** [comment]
@dhcmega You need to set `:auto="false"` on the component. Also, see #123 for manual upload - I tried it and it works well.
