### ISSUE TITLE
cant re display selected image or video that stored in data or store

### ISSUE THREAD

**Issue by alireza2281** [safrazik/vue-file-agent#133]
**Describe the bug**
I'm selecting file and store it in data of component or in store, and then navigate to other pages. when i come back to the page that file agent exists i restore the selected files to the file agent component the meta data of files would appear but the image itself wont show and when id checked the image preview tag the source is like this:

`<img src="function () { [native code] }" class="file-preview-img">`

**To Reproduce**
1.select image
2.store image data to store
3.navigate to any other pages 
4.back to prev page
5.fill v-model of file agent component with data stored in store

![image](https://user-images.githubusercontent.com/15261034/114299820-9e06fd80-9ad2-11eb-911d-031d48037429.png)

the data store in store is like this:

![image](https://user-images.githubusercontent.com/15261034/114299903-f50cd280-9ad2-11eb-836a-e86190258192.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Browser chrome
 - Version 89

**Comment by safrazik** [comment]
You only need `file` object from the `fileRecord` for storage

I have setup a [CodePen demo](https://codepen.io/safrazik/pen/VwPNorR) for you

```javascript
    onSelect(fileRecords) {
      console.log('onSelect', fileRecords);
      const fileRecordsToStore = fileRecords.map((fileRecord) => {
        // only the file object is enough for storage
        return {
          file: fileRecord.file
        };
      });
    }
```
