### ISSUE TITLE
Possibility to give the thumnail url for all file type

### ISSUE THREAD

**Issue by jalilag** [safrazik/vue-file-agent#134]
Docs, pdf... have not thumbnail
I am able to generate thumbnail of these files server side and supply an url for front side.
Is there a way to use this url instead of file icons ?

**Comment by safrazik** [comment]
Custom thumbnail is not supported yet. I'm looking into supporting it in the future.

See these related issues about custom thumbnails:
#125 #106 #66

**Comment by safrazik** [comment]
Duplicate #66
