### ISSUE TITLE
 Failed to mount component: template or render function not defined.  found in  ---> <VueFileAgent>

### ISSUE THREAD

**Issue by michaeljcoyne** [safrazik/vue-file-agent#136]
```
import VueFileAgent from 'vue-file-agent';
import VueFileAgentStyles from 'vue-file-agent/dist/vue-file-agent.css';

 components: {
            VueFileAgent,
        },
```
Getting error

 Failed to mount component: template or render function not defined.  found in  ---> <VueFileAgent>

**Comment by safrazik** [comment]
Please provide with more information. More likely your error is caused by any typo or misconfiguration. Are you sure you did `export default`

**Comment by jrtitus** [comment]
I too, have found that importing VueFileAgent as a component in a SFC results in the error mentioned by Michael. 

It seems that in order to bypass the error, it needs to be registered globally:

**main.js**
```js
import Vue from 'vue';
import VueFileAgent from 'vue-file-agent';
// Register the component globally
Vue.use(VueFileAgent);
```

**component.vue** (the piece actually using VueFileAgent)
```vue
<template>
  <vue-file-agent ... />
</template>
<script>
  import 'vue-file-agent/dist/vue-file-agent.css';
  export default { ... }
</script>

**Comment by safrazik** [comment]
@jrtitus Thanks for the heads up! @michaeljcoyne and @jrtitus if you still intend to avoid registering globally:

Please see this comment: https://github.com/safrazik/vue-file-agent/issues/31#issuecomment-566051670
and this issue: #46

**Comment by jrtitus** [comment]
Thanks @safrazik. I confirm that doing this in a SFC works, as mentioned in the other issue:

```vue
<script>
import VueFileAgentPlugin from 'vue-file-agent';
import 'vue-file-agent/dist/vue-file-agent.css';

export default {
  components: {
    'vue-file-agent': VueFileAgentPlugin.VueFileAgent,
  },
}
</script>
```

**Comment by michaeljcoyne** [comment]
Thanks I did register globally but good to know how ther other version works.

**Comment by vty21** [comment]
registering globally works for me
