### ISSUE TITLE
Remove file from queue broken when using :auto="false" ?

### ISSUE THREAD

**Issue by jrtitus** [safrazik/vue-file-agent#137]
I'm actually not sure if this is intended behavior, or not.

**Describe the bug**
When `:auto="false"` is set, clicking the `x` icon to remove a file from the queue does not remove the file.

**Expected behavior**
The file should be removed from the queue. `:auto` should only affect the auto-upload functionality.

**Workaround available**
I can still see the `beforeDelete` and `remove` events being emitted, so as a workaround, I could remove the file from the queue myself.

**Additional context**
vue-file-agent @ ^1.7.3
vue @ ^2.6.11

**Comment by safrazik** [comment]
Yes it is intended behavior. When `auto` mode is disabled, you are responsible for everything.  E.g: there could be chances where you'll need delete confirmation, etc. See the advanced demo for example.
