### ISSUE TITLE
Is t possible to pre-populate?

### ISSUE THREAD

**Issue by michaeljcoyne** [safrazik/vue-file-agent#138]
Hi can the files be prepulated like in the example?

So it can be used as a basic file manager with stored files. I imagine you would have to pass file object through.

If so please advise.

Thanks

Michael

**Comment by safrazik** [comment]
Yes, we call it `preloading`. You don't need to pass the file object - you can see several [examples](https://safrazik.com/vue-file-agent/docs/#props-demo) on the documentation sites and CodePen demos.

**Comment by safrazik** [comment]
As a matter of fact, I have successfully used it for a File Manager application. Good luck with that...!

**Comment by michaeljcoyne** [comment]
Hi thanks safrazik - I got it working however I find ext images not working as expected, event with your example. Not sure why but the rest is workng thanks. I am using spatie media library for backend  and can retrieve files I just need to see if I can delete them.
