### ISSUE TITLE
Reuse preview

### ISSUE THREAD

**Issue by Garito** [safrazik/vue-file-agent#16]
Hi!
I would like to reuse you preview component but I don't fully understand it
I have the name, the content type and the base64 data of the file
Can you explain me how to convert that to the parameters needed in the component?
Thanks

**Comment by safrazik** [comment]
Please have a look at the [Props Demo: Preloading Existing Files](https://safrazik.github.io/vue-file-agent/docs/#props-demo)

Also available at [CodePen](https://codepen.io/safrazik/pen/BaBVNEE)

As in your case, `url` can be a data uri

```javascript
  export default {
    // ...
    data: function(){
      return {
        filesData: [
           // ...
          {
            "name":"DSC_0261.jpg",
            "lastModified":1564648335292,
            "size":65762,
            "type":"image/jpeg",
            "ext":"jpg",
            "url": "https://safrazik.github.io/vue-file-agent/website/assets/files/DSC_0261.jpg"
          },
          // ...
        ]
      },
      // ...
  };
```

**Comment by safrazik** [comment]
Please fork the [CodePen](https://codepen.io/safrazik/pen/BaBVNEE) and share it here with your example if you still face issues.

**Comment by Garito** [comment]
Sorry I think you haven't understand me (which implies that I've done a bad work explaining myself)
Let me try again:
I have the name, content type and data of the files
How can I get the data structure that filesData need FROM the data I have?

Thanks

**Comment by safrazik** [comment]
> the name, content type and data of the files
Can you please provide an example (could be a fake one)
For data url, first few characters enough.

**Comment by Garito** [comment]
Url?
I have an array with dicts with { content_type: 'image/jpg', name: 'file1.jpg', data: 'data:image/jpg;base64,<the rest of the image>'}

**Comment by safrazik** [comment]
I have setup a working CodePen with your example here: https://codepen.io/safrazik/pen/YzKRPNj

Yes what your're referring to as `base64 data` of the file is the `Data URI or Data URL` of the file. Learn more about it here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

A data URI can be used where a url is required.

```javascript

     var myFiles = [
        { content_type: 'image/jpg', name: 'file1.jpg', data: 'data:image/jpg;base64,'}
     ]
      var filesData = myFiles.map(function(f, i){
        return {
            "name": f.name,
            // "lastModified":0,
            "size": getFileSizeFromDataUrl(f),
            "type": f.content_type,
            // "ext":"jpg",
            "url": f.data
          };
      });
      return {
        filesData: filesData
      };
```

**Comment by safrazik** [comment]
@Garito please let me know if your issue has been solved. Thanks for using the library. I hope there'll be more tutorials in the future.

**Comment by Garito** [comment]
I should try but I've checked the codepen

My point was that you library already have all what is needed to work but yet you have to define the function to get the file size

Whould be nice that this library was more modular and reusable

As an example of what we could do if so is to use the previews without the agent

**Comment by safrazik** [comment]
> use the previews without the agent

Thanks for the feedback. Yes this is something I’ve already planned for next version. The beauty of open source is this kind of collaboration and when the needs arise, we implement those things.

> but yet you have to define the function to get the file size

I had to do it because it’s not a good practice to get file size from base64 encoded data url. It’s not a straight forward task: I have just defined an inaccurate function there!  to get the accurate size you’ll have to decode base64, convert to blob and get the size! No, You should save that size in the DB, or return the file size from the API calculating on the server if you do it dynamically.

**Comment by Garito** [comment]
It turns out that if you create one file agent for every file, the drag and drop don't show up and ends up doing what I need (to show the same file preview that when you add it)
It has the border but good enough for me right now
I will play with the styles any time soon
