### ISSUE TITLE
Create some Unit Tests

### ISSUE THREAD

**Issue by safrazik** [safrazik/vue-file-agent#19]
Happy Hacktoberfest! 🎃
Pull requests are very welcome.

Write Unit Tests in: `tests/unit` directory. Good first candidate would be `src\lib\utils.js`

**Comment by raksit31667** [comment]
I've just started writing unit tests / refactoring `src\lib\utils.js`

**Comment by safrazik** [comment]
Thank you for your contribution.
Please do not refactor before writing unit tests because the existing code works fine. I have plans to refactor the code later, but need to write unit tests to make sure nothing is broken during refactor. So that's the whole point!
Please create tests for `src/lib/utils.js` in `tests/unit/utils.spec.js`.
Before submitting the pull request, please wait for Version 1.3.0 which I'm going to release soon (to avoid conflicts)
Thanks for help.

**Comment by safrazik** [comment]
@raksit31667 I have released version 1.3.0. Please update your fork.
