### ISSUE TITLE
Request to support TypeScript

### ISSUE THREAD

**Issue by yanqd0** [safrazik/vue-file-agent#2]
When using this (current version `1.1.1`) with TypeScript, I have to write something like this in `main.ts`:

```typescript
import 'vue-file-agent/dist/vue-file-agent.css'
import Vue from 'vue'

const VueFileAgentPlugin = require('vue-file-agent').default

Vue.use(VueFileAgentPlugin)
```

So, I hope you can support TypeScript with a `index.d.ts`.

**Comment by safrazik** [comment]
Sure. TypeScript support will be added in the next version. Pull requests are welcome though :-)

**Comment by yanqd0** [comment]
OK, I will try to submit a PR.
