### ISSUE TITLE
Add support for drag and drop reordering of uploaded files

### ISSUE THREAD

**Issue by chrispappas** [safrazik/vue-file-agent#20]
This component looks really great, one thing that would be a killer feature would be the ability to reorder the uploads using drag and drop.

A number of projects I'm working on could really use an uploader component like this, but we need to offer the ability for users to upload in a specific order, to avoid requiring a second reordering step post-upload.

**Comment by safrazik** [comment]
Sounds like a good suggestion. I will consider supporting it in the future. Currently it can be implemented with the help of slots.

**Comment by Turbotailz** [comment]
+1 for re-ordering!

Any chance of an example using slots?

**Comment by safrazik** [comment]
OK I am trying to implement a drag sort example with the famous [VueDraggable](https://github.com/SortableJS/Vue.Draggable) component from [Sortable Js](https://github.com/SortableJS/Sortable)
I will update you when the example is ready.

**Comment by safrazik** [comment]
@chrispappas and @Turbotailz  so the **"killer feature"** is finally there officially! 🎁
from [version 1.4.0](https://github.com/safrazik/vue-file-agent/releases/tag/1.4.0). Learn more [here](https://safrazik.github.io/vue-file-agent/docs/#sortable).
After a lot of testing with available solutions, I made it work with [vue-slicksort](https://github.com/Jexordexan/vue-slicksort).

```javascript
// npm install vue-slicksort --save

import { SlickList, SlickItem } from 'vue-slicksort';

Vue.component('vfa-sortable-list', SlickList);
Vue.component('vfa-sortable-item', SlickItem);
```

 `vfa-sortable-list` and `vfa-sortable-item` components should be defined for `sortable` to work

```html
      <VueFileAgent
       ...       
        :sortable="true"
        @sort="onSort($event)"
        ...
      ></VueFileAgent>
```

Thanks for bringing this up!

**Comment by chrispappas** [comment]
Awesome! Love that you took the time to implement this feature. Thank you
so much.

**Comment by Turbotailz** [comment]
I'm trying the demo but having no luck with the dragging, where is the handle to drag each item? I managed to re-order one after a lot of trial and error but couldn't do it again.

**Comment by safrazik** [comment]
@Turbotailz you have to taphold/click&hold and drag for this to work. But looking at your comment, I'm thinking of a proper implementation. What do you think? Can you please open another issue?

**Comment by Turbotailz** [comment]
Ah! Works flawlessly given that info 😅

Yes I will make another issue.
