### ISSUE TITLE
How implement a easy download button.

### ISSUE THREAD

**Issue by Atiladanvi** [safrazik/vue-file-agent#25]
I can't provide a view to list and download the files. A simple slot in the thumbnail with props url solve tha question. This is can be acceptable for the code ?

**Comment by safrazik** [comment]
Please have a look at [Pull request #24](https://github.com/safrazik/vue-file-agent/pull/24). It’s already been merged. Thanks to @codeflorist. Will be available in the next release hopefully by this weekend. Thanks for the interest to contribute. Yes I welcome any pull request but in this case it’s already done. Thanks.

**Comment by Atiladanvi** [comment]
Issue was merged in waiting release: Pull request #24

**Comment by Atiladanvi** [comment]
Issue was merged in waiting release: Pull request #24
