### ISSUE TITLE
how to work with base64?

### ISSUE THREAD

**Issue by Haizone** [safrazik/vue-file-agent#26]
i try to worl that in my nuxt app

but i didnt get how to make image with base64 i get file var empty

https://codepen.io/safrazik/pen/YzKRPNj

i see that but i didnt andersted how to put that in the example compont here

**Comment by safrazik** [comment]
Can you please look at this issue: https://github.com/safrazik/vue-file-agent/issues/16
Let me know if it didn’t help

**Comment by Haizone** [comment]
> Can you please look at this issue: #16
> Let me know if it didn’t help

hi many thanks
but still i didnt know thow to do that in my component

i make new component with your "Advanced Usage"
and i have only that Advanced Usage in my Component

how i fix that to work with Base64 and no with url
i whant to upload alone the image but i neet to send the image to my server

**Comment by safrazik** [comment]
Please have a look at [Upload Server Examples](https://github.com/safrazik/vue-file-agent/tree/master/upload-server-examples)

You can also [Download upload-server-examples.zip](https://github.com/safrazik/vue-file-agent/releases/download/1.2.0/upload-server-examples.

**Comment by safrazik** [comment]
I don't recommend using base64 to upload large files. Consider uploading binary files.

Here's an example how you can read base64 encoded dataURL:

```javascript

import {utils} from 'vue-file-agent';

// ...
utils.getDataURL(fileData.file).then((dataURL)=> {
  // base64 encoded dataURL
});
// ...

// utils.getDataURL for reference
getDataURL(file){
  return new Promise((resolve, reject)=> {
    var reader = new FileReader();
    reader.onload = (readerEvent)=> {
      resolve(readerEvent.target['result']);
    };
    reader.readAsDataURL(file);
  });
}
```
