### ISSUE TITLE
Drag/drop sorting is not very intuitive

### ISSUE THREAD

**Issue by Turbotailz** [safrazik/vue-file-agent#30]
On the demo page, `Drag & drop sortable` is checked but does not display any info on how to actually do so. I asked and was told to click and *hold* to activate it (source: https://github.com/safrazik/vue-file-agent/issues/20#issuecomment-560250367)

I would suggest adding a "handle" area on the items that users could click and drag on to active the sortable feature.

**Comment by safrazik** [comment]
I'm thinking of making the `sortable` property little more configurable.
e.g:
`sortable: true` - just drag and sort (works best when enabled/disabled with external controls)
`sortable: 'hold'` - hold to activate
`sortable: 'handle'` - drag with handle

What do you think?

**Comment by safrazik** [comment]
@Turbotailz `sortable` is now configurable as above mentioned. ([v 1.4.2](https://github.com/safrazik/vue-file-agent/releases/tag/1.4.2))

use `sortable-handle` slot to customize the handle icon

https://safrazik.github.io/vue-file-agent/docs/#sortable
