### ISSUE TITLE
$ref typings?

### ISSUE THREAD

**Issue by evry-johan** [safrazik/vue-file-agent#34]
Hi,

I'm using your advanced sample code. Since I'm using typescript, I would like a typed $ref from the VueFileAgent component. 

My question is, what should I cast the component ref to? As far as I can tell, there is no typing exported to support this. A mixin seems to be applied with the methods I'm after (upload, deleteUpload etc), but vscode doesn't pick that up as far as intellisense goes.

**Comment by safrazik** [comment]
Did you try `typeof`?

```typescript
import {VueFileAgentMixin} from ‘vue-file-agent’;

// ...
type VueFileAgentComponent = typeof VueFileAgentMixin;
// ...
```

**Comment by evry-johan** [comment]
> Did you try `typeof`?
> 
> ```ts
> import {VueFileAgentMixin} from ‘vue-file-agent’;
> 
> // ...
> type VueFileAgentComponent = typeof VueFileAgentMixin;
> // ...
> ```
> 
> (This can be considered as a workaround for now)

Thanks for the suggestion. Even if I use `typeof VueFileAgentMixin` as the ref type, it still seems to be considered a `VueConstructor` from the IDE's point of view.

**Comment by safrazik** [comment]
Sorry for the untested suggestion. I will provide a better implementation for the advanced upload handling (hopefully in the next update).

Please use another workaround with a custom interface until then.

```typescript
interface VueFileAgentComponent {
  upload(url: string, headers: object, filesData: any[]): Promise<any>;
  deleteUpload(url: string, headers: object, fileData: any, uploadData?: any): Promise<any>;
};

// ...

(this.$refs.vueFileAgent as VueFileAgentComponent).upload('/endpoint', {}, []);

// ...
```

Thanks for using the component.

**Comment by evry-johan** [comment]
@safrazik No worries, thanks for the workaround and a nice plugin!
