### ISSUE TITLE
Cross-site upload with credentials

### ISSUE THREAD

**Issue by pibi** [safrazik/vue-file-agent#36]
Hi. I need to upload some files from an app to a server located in another domain. I currently using cookie based authentication, so, I should set `withCredentials: true` to the request.

I see in the code that there's no way to do that directly, so, could you please add an option to support this use case? Is there any alternative approach I could explore?

Thanks!

**Comment by safrazik** [comment]
If you look at the [upload-helper](https://github.com/safrazik/vue-file-agent/blob/master/src/lib/upload-helper.ts#L30), you can see that there is a `configureFn` which can be used for your purpose, but it has not been utilized properly yet in the component. I’ll add this functionality in the next beta version immediately (hopefully tomorrow) so you can use it right away like this:

```javascript
(xhr) => {
  xhr.withCredentials = true;
}
```

Thanks for using the library.

**Comment by safrazik** [comment]
New prop `uploadWithCredentials` added. [See the Docs](https://safrazik.github.io/vue-file-agent/docs/#uploadWithCredentials)

```vue
<VueFileAgent
  :uploadWithCredentials="true"
></VueFileAgent>
```

Also new prop `uploadConfig` added. [See the Docs](https://safrazik.github.io/vue-file-agent/docs/#uploadConfig)

See also: `upload` and `deleteUpload` [methods](https://safrazik.github.io/vue-file-agent/docs/#methods)
