### ISSUE TITLE
Preloading existing files no longer works.

### ISSUE THREAD

**Issue by born2discover** [safrazik/vue-file-agent#37]
Hello there,

First of all let me start by saying great work on the uploader. It's really neat and works pretty well!

However I got a question about the preloading of existing files. While documentation does describe that feature, it does not seem to work, that is, even though store provides the list of files to the vue-file-agent, those files do not appear.

I also checked out the CodePen demo and it also does not seem to show existing files.

**Comment by safrazik** [comment]
Thanks for addressing the issue. The CodePen demo has been updated now. I have updated the demo site from https://safrazik.github.io/vue-file-agent/ to https://safrazik.com/vue-file-agent/ and there are still some references to the old url. It caused the files to disappear.
https://codepen.io/safrazik/pen/BaBVNEE

The error with the wrong url should have been handled gracefully. So I think it’s a separate issue on its own. I will open a new issue for that and fix it soon.

If you still don’t get it to work, please explain the issue with some code.

**Comment by born2discover** [comment]
First of all thank you for a quick reply!

After some deep debugging I was able to ascertain that issue was indeed unrelated to vue-file-agent and was caused by a weird interaction within my own codebase.
Apologies for the trouble.
