### ISSUE TITLE
Upload event does no longer work

### ISSUE THREAD

**Issue by ben182** [safrazik/vue-file-agent#38]
The `@upload="onUpload"` event on the `VueFileAgent` element does not work anymore for a couple of days. Earlier I could grab the uploaded files with something like that `onUpload(addedFiles)`. Now the addedFiles variable returns undefined.

**Comment by safrazik** [comment]
It could be possibly because of the latest changes in beta version (`1.5.3-beta.1` - published 5 days ago)
Can you use the previous beta version  `1.5.3-beta.0` and see if it's fine?
The `upload`, `upload:error` events, etc. will be available in final `1.5.3` version with docs.

**Comment by ben182** [comment]
Thanks for the quick response. Yes that does seem to fix it. So this will be working in the final 1.5.3?

**Comment by safrazik** [comment]
Yes. It's is part of version `1.5.3` features. Thanks for reporting the issue. Glad you found the feature useful.
