### ISSUE TITLE
Cannot use in my SFC

### ISSUE THREAD

**Issue by mrlinnth** [safrazik/vue-file-agent#46]
I got

```
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <VueFileAgent>
       <FtmTest> at resources/js/components/filetinmel/FtmTest.vue
         <Root>
```

My FtmTest.Vue is

```vue
<template>
    <div>
        <p class="foo mt-10">hello from test component</p>
        <VueFileAgent :uploadUrl="uploadUrl" v-model="fileRecords"></VueFileAgent>
    </div>
</template>

<script>
import VueFileAgent from 'vue-file-agent'
import VueFileAgentStyles from 'vue-file-agent/dist/vue-file-agent.css'

export default {
  components: {
    VueFileAgent
  },
  data () {
    return {
      fileRecords: [],
      uploadUrl: '/api/filetinmel/s3'
    }
  }
}
</script>
```

Adding the library globally works.
But I would like to use this locally in my necessary single file components instead of globally.

Am I doing it wrong? Hope someone can assist me.

**Comment by safrazik** [comment]
Please have a look at issue #31

Have a look at [src/index.ts](https://github.com/safrazik/vue-file-agent/blob/master/src/index.ts) to understand how the built in plugin works right now.

Even though officially not documented, it’s easy to be done. If you make it work, please share your solution here for others.

**Comment by mrlinnth** [comment]
Wow, thank you so much @safrazik . It is working now. I am not familiar with typescript and not very good at Vue yet. Much appreciated.

Below code works.

```js
import VueFileAgentPlugin from 'vue-file-agent'
import VueFileAgentStyles from 'vue-file-agent/dist/vue-file-agent.css'

export default {
  components: {
    'vue-file-agent': VueFileAgentPlugin.VueFileAgent
  },
  data () {
    return {
      fileRecords: [],
      uploadUrl: '/api/filetinmel/s3'
    }
  }
}
```
