### ISSUE TITLE
Can you, please, add "capture" option over input file? Or how can I add this option?

### ISSUE THREAD

**Issue by Gigiart** [safrazik/vue-file-agent#48]
Can you, please, add "capture" option over input file? Or how can I add this option?

**Comment by safrazik** [comment]
Thanks for asking.
It's not available yet. I will add it in the next version. Hopefully by tomorrow.

**Comment by safrazik** [comment]
Feature added in `v 1.6.2`

```vue
<VueFileAgent
  capture="user"
></VueFileAgent>
```
