### ISSUE TITLE
Hi, I need Pure VueJS example of VueFileAgent.

### ISSUE THREAD

**Issue by PremiumNoFreemium** [safrazik/vue-file-agent#49]
Hi, this is not and issue generally but it is issue for us.
We need Pure VueJS example of VueFileAgent. Because we've some problems with TS(typescript).
We tried to install it with npm and yarn too. But failed because of some typscript issues.
Before that we cut out fully .TS file support from VueJS and now it was working. But we need help to great things with VueFileAgent..
We are going to use it in an E-commerce app. Just can you share it in a .Vue file so then we can use it globally in our project. If you help with this problem It will be great and we use it to an E-commerce website for Germany, UK and Uzbekistan. So we hope you can do this. Thank you in advance. Of course we specify which library was used to create such thing in the license part of website.
So we say:
|||||| **We used some useful VueJS library called "vue-file-agent" to build our uploaders. So great thanks to https://github.com/safrazik who is the creator of this file. Any copyright of this library belongs to him. For more info go with this url: https://github.com/safrazik/vue-file-agent** ||||||

Sorry, If any misunderstanding words,
This was just the help of Google Translator.

Thank you again.

With warm regards Otabek from UzbekDEVs programming community.

**Comment by safrazik** [comment]
First of all, thank you for using my library in your project. Glad to hear that.

Coming to your question: I find it little confusing. If you could mention the error, I would be able to help. Please mention the version of the library you faced the issue as well.

Are you looking for an example in TypeScript or in JavaScript? FYI: all the examples in doc site and CodePen use only JavaScript.

Please have a look at this common TypeScript related issue https://github.com/safrazik/vue-file-agent/issues/33

**Comment by PremiumNoFreemium** [comment]
Hi, Just we said about example code of the uploader which we see it when we opened https://safrazik.com/vue-file-agent/. And is there ``.vue`` file of that uplaoder?
We want to use it in out e-commerce project. If the project runs and begin giving income even we can be sponsor for you. Just between 30$ and 50$. Just we fully removed .ts support.
So we need pure ``.vue``, namely, ``js`` example. We use it as global component. And just it is for uploading images when leaving review. Just we don't have problems with .ts. Simply we get rid of it with the help of some **Vue Masters**. And even I think you can do that.

Here is the image what we want to see in just a or 2 vue files.
![image](https://user-images.githubusercontent.com/60849894/78927679-bb1c8100-7ab8-11ea-8b07-26ea8cd22db0.png)

I believe you can do it. Thank you for reading. We hope you will provide with such thing soo.

With warm regards Otabek from UzbekDEVs programming community

**Comment by safrazik** [comment]
Thank you for your concern. I really appreciate it.

I think I understand your question now, hopefully. As you are facing issues, you want to include the library source code directly in your code. You can do it in two ways.

### 1. First way

You can download the latest version of this file (save to disk): https://raw.githubusercontent.com/safrazik/vue-file-agent/master/dist/vue-file-agent.umd.js
And include in your project source file like this:

```javascript
import Vue from 'vue'
import VueFileAgent from './vue-file-agent.umd'

VueFileAgent.use(Vue)
```


### 2. Second way

You can download this source code and include in your project: https://github.com/safrazik/vue-file-agent/archive/1.4.2.zip
Use the files from `src` directory. Have a look at `App.vue` for inspiration.

Explanation:

The Vue file agent library went through a major code refactor in [version 1.5](https://github.com/safrazik/vue-file-agent/releases/tag/1.5.0)
If you look at [source code prior to that version](https://github.com/safrazik/vue-file-agent/tree/1.4.2/src) you can see that all the code was in JavaScript. 

- - -

If I still haven’t understood you well, please give me example of your code usage, so I can help. Feel free to ask.

**Comment by safrazik** [comment]
The demo `vue`  files used in the website is at https://github.com/safrazik/vue-file-agent/tree/master/src/demo

The file used for the screenshot you shared is here: [demo-basic.vue ](https://github.com/safrazik/vue-file-agent/blob/master/src/demo/demo-basic.vue)

**Comment by PremiumNoFreemium** [comment]
Yeap really this is what I want. I am so happy to see your library in  ``licenses-and-libraries`` namely, **about what the things used in website section**.

**Comment by safrazik** [comment]
Thanks again for using my library. Glad it worked for you.
