### ISSUE TITLE
Feature Rename Files ?

### ISSUE THREAD

**Issue by lookingdown** [safrazik/vue-file-agent#5]
Hi there..
Looking good your uploader :)
Have any plans to add rename of uploaded files..
Something apparently simple like having filenames now present in list and thumbnails view editable or whatever unobtrusive way.. 

Makes sense when uploading camera photos like DSCN87682746.jpg to let the user determine name at the time of upload files becomes identifiable and searchable by name..
Thanks

**Comment by safrazik** [comment]
I believe that it should be your server side's responsibility (to auto name with a unique id, etc)
But if there is really a demand for it, we can support it with an edit icon maybe. My concern is that it could complicate the simplicity of the component.

Even if it is supported in the future, it should be enabled via an extra prop like `editable` similar to the existing `deletable` prop.

**Comment by lookingdown** [comment]
Ok..
Server would not know about what to name each file unless it receives the value in the post data the filename would be the simplest would work with all backends if you had a editable field could be the same filename made editable by editable prop and include that value in filedata array.. most transparent would be the filename on the thumnail be editable if prop enable in that way does not take a way from simplicity funcionally or visibly.  
I would also suggest the ability to add data to formdata in my case 
formData.append('action', 'upload'); 
for the fileupload api to trigger upload. 
Thanks
/

**Comment by safrazik** [comment]
Currently it’s possible through an extra input field but that’s not practical for multiple files - so it would be cool to have built in support. Will be added in the next version (perhaps after adding tests) Thanks for bringing this up.

By the way, Please open another issue for your formData - that featured can be easily added, but remember, every file is uploaded independently (simultaneously).

**Comment by lookingdown** [comment]
Thanks for considering..
My use for this library is within a filemanager and filepicker used both standalone and with tinymce.
The idea is to only allow upload of files within the filemanager as the server side implementation creates 4 versions of different sizes and properties and these are subsequently selectable from the filemanager when accessed as filepicker as select value but the enduser only sees one version the original.  The use is geared towards completely non technical users and allows simple logical access.

Your library is perfect due to its simplicity in presentation and with large (configurable size) thumbnails and easily understandable visual presentation, very good indeed.  
It might be a killer features for my potential users to have single name for an upload batch. Have not seen this but your reply inspired some thinking.  For instance the user have 20 fotos to upload from vacation in portugal August 2019 (for example) to be able to tag the upload could be very interesting from a useability standpoint for photo management. On server side I would be able to tag the upload batch or name, on server side have the option the to name the filebatch the inoutted name like Portugal august 2019-1.jpg thought to Portugal august 2019-20.jpg or simply tag the files with an exif value or DB entry..

Just some thoughts.

Thanks again

**Comment by safrazik** [comment]
Sounds good. Out of curiosity, is it an open source or commercial one? (Both are fine) has it been already developed? if you are in a situation not to disclose anything - just ignore this question. If you want me to feature it on the website, please let me know.

**Comment by safrazik** [comment]
@lookingdown File name edit feature added. Please have a look and provide feedback:
You can click on the **file name** to edit it
https://safrazik.github.io/vue-file-agent/#advanced-demo
