### ISSUE TITLE
How can I change image preview background

### ISSUE THREAD

**Issue by lelikflegma** [safrazik/vue-file-agent#52]
Hi. Currently, when I upload image, preview background-color is calculated and settled like average color of uploaded image. So, for original PNG, with transparent body
![image](https://user-images.githubusercontent.com/62481624/79118009-50f42c80-7d95-11ea-9db7-5f751e7bf200.png)
I got :
![image](https://user-images.githubusercontent.com/62481624/79117936-24401500-7d95-11ea-970d-36fa703e6c46.png)

I found in html this :
```
<span class="file-preview image-preview" style="background-color: rgb(80, 65, 250);">
```
When i comment style, i got this :
![image](https://user-images.githubusercontent.com/62481624/79118288-2eaede80-7d96-11ea-94bd-23566aa1999d.png)

For remove gray backround i can override css property "background" in :
```
.vue-file-agent .file-category-video-playable .file-preview .file-preview-overlay, .vue-file-agent .file-preview-wrapper-image .file-preview .file-preview-overlay {...}
```
![image](https://user-images.githubusercontent.com/62481624/79118746-5f434800-7d97-11ea-8533-25d20d0cf465.png)

and for remove grid :
```
.vue-file-agent .file-preview .file-preview-img {...}
```
![image](https://user-images.githubusercontent.com/62481624/79118846-a2052000-7d97-11ea-8ba0-92d90e73842c.png)

But how can I remove setting "average" color background ?

In source code i found function :
```
public color(): string {
    if (this.imageColor) {
      const rgb = this.imageColor;
      return 'rgb(' + rgb[0] + ', ' + rgb[1] + ', ' + rgb[2] + ')';
    }
    if (this.isImage()) {
      return 'transparent';
    }
    const ext = this.ext();
    const svgIcon = this.icon();
    // var svgIcon = getIconFromExt(ext);
    if (svgIcon.color) {
      return svgIcon.color;
    }
    return utils.getColorForText(ext);
  }
```

And property imageColor :
```
imageColor: RGBA;
```

**Comment by safrazik** [comment]
I think, having a property to disable this feature will be the ideal solution for this. But for the time being, you can use a CSS workaround. Note the usage of `!important`

```css

.vue-file-agent .file-category-video-playable .file-preview,
.vue-file-agent .file-preview-wrapper-image .file-preview {
  background: transparent !important;
}

```

**Comment by lelikflegma** [comment]
Yes it works like that, thanks.
But having property will be better.

**Comment by safrazik** [comment]
Yes, with the property, the operation to calculate the average color can be avoided too.

Instead of `transparent` background you can try other colors like `white` and `black` too.
