### ISSUE TITLE
Only show the first file when multiple is true.

### ISSUE THREAD

**Issue by davs20** [safrazik/vue-file-agent#60]
I'm using a CDN version , and when i set the multiple prop true, only load the first file of the selection, this only happen the first time that component has been mounted, if i try a second time, works normally.

ENV
Windows 10
Vue 2.6.11
Google Chrome   81.0.4044.138

**Comment by davs20** [comment]
I solved the problem, it was very simple, there was a function in my code that modified v-model changing it from array to null

**Comment by safrazik** [comment]
Yes, multiple mode requires an array value. You can modify/empty the array, but shouldn’t reassign another non-array value.

```html
<VueFileAgent
  v-model="fileRecords"
</VueFileAgent>
```
```javascript
export default {
  data() {
    return {
      fileRecords: []
    }
  },
  methods: {
    exampleResetMethod() {
      // this.fileRecords = null; // NOT ok
      this.fileRecords = []; // ok
    }
  }
}
```
