### ISSUE TITLE
access dimensions before upload? 

### ISSUE THREAD

**Issue by bkarlson** [safrazik/vue-file-agent#61]
Hello,
I'm using a sort-of custom upload fn: 

```js
                    @select="uploadImage($event)"
```

But when I try to access dimensions object from `uploadImage`, it returns `{"width":0,"height":0}` even when put in `nextTick`. If I check component data in DevTools, I can see that dimensions are set correctly, but I guess it happens later, I just cannot figure out when.

My quesion is: 

- what's the correct way to create a custom upload fn that fires on select (i.e. without pressing a button, same as automatic upload basically) and receives up-to-date fileRecord?

Thanks for the great lib!

**Comment by safrazik** [comment]
Your issue addresses a minor issue in the library. I was able to reproduce in the [CodePen demo](https://codepen.io/safrazik/pen/BaBpYme). I will do a quick fix in the next version.

For implementing a custom uploader, please have a look at the [built in uploader](https://github.com/safrazik/vue-file-agent/blob/master/src/lib/upload-helper.ts) and the [advanced demo](https://github.com/safrazik/vue-file-agent/blob/master/src/demo/demo-advanced.vue) for inspiration

---

Notes on the events (from [the docs](https://safrazik.com/vue-file-agent/docs/#events)):

`input` event: Fired whenever files are selected. Passes all selected files data (including previously selected). You shouldn’t use this event directly. Instead, use v-model for two way binding, and use select event for other purposes

`select` event: Fired whenever files are selected. Passes the (newly selected) files data.

**Comment by bkarlson** [comment]
Thanks for prompt follow up!

Overall, I think it can be useful to add dimension checks prior upload with a custom error message (similar to file-type and size checks). 

Also, please note another potential issue: in your pen, add `:max-files="1"` and try to drop one file, then another: this will cause to `toSelect` to receive an empty array, i.e. fileRecord is lost. Without `max-files` everything works as expected (every dragged file is received properly).

![image](https://user-images.githubusercontent.com/30080507/81839717-1e934600-9572-11ea-84d1-c922a9878727.png)

**Comment by safrazik** [comment]
From the version `1.7.2` you won't see the 0 dimension error.

> Overall, I think it can be useful to add dimension checks prior upload with a custom error message (similar to file-type and size checks).

I think you're talking about validation on dimension. Haven't thought about it yet. Maybe it could be implemented in the future, or at least an implementation of some way to define custom validations.

I will have a look at the other issue you're talking about.

Thanks for reporting the issues. Thanks for using the library. Enjoy!

**Comment by safrazik** [comment]
That was a weird issue only happened when `:multiple="false"`

Version `1.7.3` fixes the issue (ignores the `maxFiles` config in single mode, since only one file is processed)
