### ISSUE TITLE
CORS error @ 1.7.1 with preloaded images

### ISSUE THREAD

**Issue by bkarlson** [safrazik/vue-file-agent#62]
Seems like it's related to #54, but the problem still exists in 1.7.1, see repro: 
https://codepen.io/bkarlson/pen/GRpXVpW

Error: 
```
Access to image at 'https://i.guim.co.uk/img/media/9c2eca9ce4122764ac7244e30236e7d8af4eab77/480_656_2948_1769/master/2948.jpg' 
from origin 'https://cdpn.io' has been blocked by CORS policy:
 No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
In my project such preloaded images load fine, but CORS error is still thrown. No probs on same domain requests of course.

**Comment by safrazik** [comment]
Thanks for reproducing the issue. Will have a look.

**Comment by safrazik** [comment]
The image url you referenced returns a non-image response 401 header: https://i.guim.co.uk/img/media/9c2eca9ce4122764ac7244e30236e7d8af4eab77/480_656_2948_1769/master/2948.jpg

You may need to open this page in incognito mode as you might have logged in to the image service.

Image tag here:
```html
<img alt="Preview Image" src="https://i.guim.co.uk/img/media/9c2eca9ce4122764ac7244e30236e7d8af4eab77/480_656_2948_1769/master/2948.jpg">
```

Result:
<img src="https://i.guim.co.uk/img/media/9c2eca9ce4122764ac7244e30236e7d8af4eab77/480_656_2948_1769/master/2948.jpg" class="file-preview-img">

**Comment by bkarlson** [comment]
my bad, image link has expired. I updated codebin with another URL, please re-check.
Any domain that does not provide CORS heades witll cause such error in console.

**Comment by safrazik** [comment]
I see the issue now. But the image shows up in the preview, right? The error should have been thrown during the resize/average color calculation operation. Investigating...

**Comment by safrazik** [comment]
Unfortunately, it appears to be an issue that can't be fixed.

The only thing that'll be missing from non CORS enabled images is - average/seamless background color. At least the image is shown in preview. The console error is a system thrown error - impossible to suppress.

Here's an explanation:
https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

Here's a similar issue: https://github.com/Foliotek/Croppie/issues/380

**Comment by bkarlson** [comment]
Thanks for the explainer, makes sense now.
