### ISSUE TITLE
No File Chosen label

### ISSUE THREAD

**Issue by clement-berard** [safrazik/vue-file-agent#68]
Hi and thank you for your work :) 

When I put pictures in the `v-model`, they load well and display well. However it is written: No File Chosen

![COCO12345](https://user-images.githubusercontent.com/38923547/83675813-f11e4300-a5d9-11ea-8c12-8efd2a47c8ef.png)

Do you have an idea ? 

Best,

**Comment by safrazik** [comment]
Are you not including the CSS styles?

If you are using custom CSS styles, you must hide the file input some way, but making it clickable - refer to the default styles provided with library.

I recommend including the default styles and customizing on top of that - that’s the way list theme was created.

**Comment by clement-berard** [comment]
It work !!

thanks a lot, 

great job :) 

Best regards
