### ISSUE TITLE
Sorting order not working as needed

### ISSUE THREAD

**Issue by shafimpk** [safrazik/vue-file-agent#72]
Hi,

I just used the advanced demo code, everything is working perfect and thanks for the awsome work. 
However when I save after sorting , its not saving as the sorted way. Its saving only the way its uploaded. So it there a way to pass the sort order value or something. Please advice. I tried for 2 days and no luck.

**Comment by safrazik** [comment]
I don't understand what you mean by "save" after sorting. The component sorts the array passed via `v-model`. You can listen to `sort` event to trigger any actions after sorting. In the advanced demo, you can see the console output after sorting.
Consider this example:

```html
 <VueFileAgent
    v-model="fileRecords"
    @sort="onSort($event)"
  ></VueFileAgent>
```

```javascript
  export default {
    data: function () {
      return {
        fileRecords: [],
        // ...
      };
    },
    methods: {
      onSort: function () {
        // You get the fileRecords array sorted already
        console.log(this.fileRecords);
      },
    },
  };
```

If you can show some example code for your particular problem, I may be able to help.

**Comment by shafimpk** [comment]
`<VueFileAgent
    :auto="false"    
    ref="vueFileAgent"
    :theme="'grid'"
    :multiple="true"
    :sortable="enableDrag"
    :deletable="true"
    :meta="true"
    :accept="'image/*,.zip'"
    :maxSize="'10MB'"
    :maxFiles="14"
    :helpText="'Choose image `files'"`      
    @select="filesSelected($event)"
    @beforedelete="onBeforeDelete($event)"
    @delete="fileDeleted($event)"
    @sort="onSort($event)"
    v-model="fileRecords"
  ></VueFileAgent>`


`export default {
    props:{
        submitUrl:{
            type:String
        },
        data:{
          type:String
        }
    },
    data: function () {
      return {
        enableDrag:false,
        fileRecords: [],
        uploadUrl:this.submitUrl ,        
        uploadHeaders: { 'X-Test-Header': 'vue-file-agent' },
        fileRecordsForUpload: []
      };
    },
    methods: {
      onSort:function(){

        console.log(this.fileRecords)
      },
      uploadFiles: function () {
        // Using the default uploader. You may use another uploader instead.
        this.$refs.vueFileAgent.upload(this.uploadUrl, this.uploadHeaders, this.fileRecordsForUpload);
        this.fileRecordsForUpload = [];
      },
      deleteUploadedFile: function (fileRecord) {
        // Using the default uploader. You may use another uploader instead.
        

         axios.post('/upload/delete', this.fields).then(response =>{         
           
            console.log(response)
        }).catch(error =>{
         

        })



        // this.$refs.vueFileAgent.deleteUpload(this.uploadUrl, this.uploadHeaders, fileRecord);
      },
      filesSelected: function (fileRecordsNewlySelected) {
        var validFileRecords = fileRecordsNewlySelected.filter((fileRecord) => !fileRecord.error);
        this.fileRecordsForUpload = this.fileRecordsForUpload.concat(validFileRecords);
        
       
      },
      onBeforeDelete: function (fileRecord) {
        var i = this.fileRecordsForUpload.indexOf(fileRecord);
        if (i !== -1) {
          this.fileRecordsForUpload.splice(i, 1);
        } else {
          if (confirm('Are you sure you want to delete?')) {

             this.deleteUploadedFile(fileRecord) // will trigger 'delete' event
          }
        }
      },
      fileDeleted: function (fileRecord) {
        var i = this.fileRecordsForUpload.indexOf(fileRecord);
        if (i !== -1) {
          this.fileRecordsForUpload.splice(i, 1);
          console.log('deleted')
        } else {
          this.deleteUploadedFile(fileRecord);
        }
      },
    },
  };`




This is the code i'm using . I have not changed much from the code you provided in the advanced demo . Im still working around. 

My requirment: When the image is sorted I need to save the image in the same sorted way. But now its not happening. So Im not sure how to get the sorted Value.

**Comment by safrazik** [comment]
Saving the sort order is solely your application's responsibility. I can give you a few directions:

1. You can store the meta information including the sort order in a persistent storage like database.
2. You can (re)name the file on the server to a sequence name based on the sorting order.
3. You can save the file content and meta in database (similar to 1.) - depends on your server infrastructure.

Also note that, as files are uploaded parallelly not sequentially, you need to send the sort order to server in a separate request.

**Comment by shafimpk** [comment]
Hi, Thanks for your advice. The points mentioned by you is what I am planning to do. But my doubt is how should I pass or how will I get the sort order. Since the images are uploaded parallel, what is the way to get the sorting order

**Comment by safrazik** [comment]
Your best bet is to create a custom uploader based on the default uploader or any external uploaders. I f you think it should be implemented in the default uploader, please feel free to customize and send me pull request. Thanks. Otherwise, it's easy to send an ajax request to server with sorted file meta. E.g:

```javascript,
      uploadFiles: function () {
        var order = 1;
        var sortedMetaArray = this.fileRecordsForUpload.map(function(fileRecord){
          return {
            name: fileRecord.name,
            sortOrder: order++,
            // ...
          };
        });
        sendSortedMetaArrayToServerAjax(sortedMetaArray).then(function(){
          // meta array is sent already
          this.$refs.vueFileAgent.upload(this.uploadUrl, this.uploadHeaders, this.fileRecordsForUpload);
          this.fileRecordsForUpload = [];
       });
      },
```

**Comment by shafimpk** [comment]
Ok. Thanks . I suggest to add this in the default uploader.

**Comment by shafimpk** [comment]
Hi, 

One last issue.  When i try to do as you mentioned here in the onSort function, I'm not getting the filename.  Please check the code and console log of the output as follows

```
<script> 
  export default {
 methods: {
      onSort:function(){
        var order = 1;
        var sortedMetaArray = this.fileRecords.map(function(fileRecord){
          console.log(fileRecord)
          return {
            name: fileRecord.name,
            sortOrder: order++
          };
        });
        console.log( sortedMetaArray);
       
      }
}
}
</script> 
```


This is the console log of the  sortedMetaArray
![image](https://user-images.githubusercontent.com/13327438/84626875-f4c59a00-aef6-11ea-9124-dbf153afe27c.png)

How can I just get the filename only from here.
