### ISSUE TITLE
Template Image preview

### ISSUE THREAD

**Issue by dariocf1** [safrazik/vue-file-agent#73]
Hi, 

I'm new in Vue development and your component simplifies some task for me, Thanks.

I want to add a button at the side of the image preview, I saw you have file-preview slot, as you know, if I put some inside, overwrites all.

How Can I get the standar code for image preview  to use it and add a button ?

<img width="456" alt="Screen Shot 2020-06-11 at 13 41 48" src="https://user-images.githubusercontent.com/21064656/84427266-449c1c80-abea-11ea-9333-e14bc04ead0e.png">

I'm also using sorteable and editable properties.

Thanks in advance

**Comment by safrazik** [comment]
Adding `file-preview-before` and `file-preview-after`

**Comment by safrazik** [comment]
It is not possible at the moment. Adding `file-preview-before` and `file-preview-after` slots will be the ideal solution. Will add it in the next update.

---
Sorry the issue was closed by mistake.

**Comment by dariocf1** [comment]
I Thank you for consider to add slots to solve this. I will wait for the next update.

**Comment by safrazik** [comment]
`file-preview-before` and `file-preview-after` slots are added. You will need to add custom CSS for your needs. Sortable feature will not be affected.

```vue
<template>
  <VueFileAgent class="my-file-agent">   
    <template v-slot:file-preview-after="{ fileRecord, index }">
      <span class="file-preview-button">Button</span>
    </template>
  </VueFileAgent>
</template>
<style>
  .my-file-agent .file-preview-wrapper .file-preview {
    width: calc(100% - 50px);
  }
  .my-file-agent .file-preview-button {
    position: absolute;
    z-index: 11;
    width: 50px;
    height: 100%;
    right: 0;
    background: yellow;
    border: 2px solid red;
  }
</style>
```
