### ISSUE TITLE
Upload images with existing images, gives error

### ISSUE THREAD

**Issue by shafimpk** [safrazik/vue-file-agent#74]
Hi,

When I try to load existing images, then upload new image to the collection and upload, only new images getting uploaded. Existing or old images gives error from server.

I can see the uploaded file format is showing [object object ] instead of (binary).

Please suggest me the expect way to do it
![image](https://user-images.githubusercontent.com/13327438/84590583-ef117b00-ae48-11ea-820f-124760941adc.png)

for newly uploaded:

![image](https://user-images.githubusercontent.com/13327438/84590596-0b151c80-ae49-11ea-8164-8920eb2da5cc.png)

code used to initialize existing data:

```
export default {
 props:{       
        images:{
          type:String
        }
    },
created(){

      var data = JSON.parse(this.images)
      for(var i = 0; i < data.length; i++) {       
          var obj ={
            name: data[i].link,
            id: data[i].id,
            url: "https://localhost.test/images/properties/"+data[i].link,
            type:"image",
            ext: "jpg",
            size: 123
          }
        
        this.fileRecords.push(obj)
        this.fileRecordsForUpload.push(obj)
      }
    }


}
```

**Comment by safrazik** [comment]
You should not upload existing images - again! If the array `fileRecordsForUpload` consists of fileRecords to upload, you should not add existing files to this array. Remove this line:
```
this.fileRecordsForUpload.push(obj)
```

**Comment by shafimpk** [comment]
So in that case, If I upload new images and changed the sorting order then how I will be able to update sorting order which is a mix of both new and existing?


Thanks and really appreciate your quick responses

**Comment by safrazik** [comment]
As mentioned in issue #72 you should create another api endpoint in your app to request for sorting order. This time, it's better to listen to `sort` event and call the `sendSortedMetaArrayToServerAjax` that sends request to the aforementioned api endpoint. This way, your sorting feature will work as a standalone feature, not depending on file uploads.
Earlier my suggestion in your issue #72 only considered uploaded files. (Note the difference in `this.fileRecords.map...` from `this.fileRecordsForUpload.map...`) Hope you get the idea.

```javascript
      onSort: function () {
        var order = 1;
        var sortedMetaArray = this.fileRecords.map(function(fileRecord){
          return {
            name: fileRecord.name,
            sortOrder: order++,
            // ...
          };
        });
        sendSortedMetaArrayToServerAjax(sortedMetaArray); // standalone sorting operation. Make sure to catch errors!
      },
```

**Comment by shafimpk** [comment]
great! Thanks alot . Got the idea
