### ISSUE TITLE
How can i implement the "ExtendedVue" Mehtodes

### ISSUE THREAD

**Issue by HoehensteigerGames** [safrazik/vue-file-agent#75]
hi,

i love the vue-file-agent. I am working with Typescript and now i am trying to implement the correct way to get the type or the mehtodes in my project without declaring as any.
I imported the tag with the refs:
![image](https://user-images.githubusercontent.com/58444802/85222376-b4649100-b3ba-11ea-9c45-1e60c5efdb45.png)

And now i am using the methode to get the refs.
![image](https://user-images.githubusercontent.com/58444802/85222387-d52ce680-b3ba-11ea-8e5a-f5bb2e724682.png)
As you can see i have to declare the refs as "any". otherwise i will receive an error message:
![image](https://user-images.githubusercontent.com/58444802/85222407-03aac180-b3bb-11ea-9650-0996c38fc23d.png)
What is the correct way to use a typesave way.

Thank you.

**Comment by safrazik** [comment]
Better typescript support with lot of improvements in events and method is coming in `v2`. Please use the following `VueFileAgentComponent` interface until then.

```typescript
interface FileRecord {
    file: File;
}

interface VueFileAgentComponent {

    deleteFileRecord(fileRecord: FileRecord): void;

    upload(
        url: string,
        headers: object,
        fileRecords: FileRecord[],
        createFormData?: (fileRecord: FileRecord) => FormData,
        configureXhr?: (request: XMLHttpRequest) => void,
    ): Promise<any>;

    updateUpload(
        url: string,
        headers: any,
        fileRecord: FileRecord,
        uploadData?: any,
        configureXhr?: (request: XMLHttpRequest) => void,
    ): Promise<any>;

    deleteUpload(
        url: string,
        headers: any,
        fileRecord: FileRecord,
        uploadData?: any,
        configureXhr?: (request: XMLHttpRequest) => void,
    ): Promise<any>;

};
```

Usage:
```typescript
(this.$refs.vueFileAgent as VueFileAgentComponent).upload('/endpoint', {}, []);
```

**Comment by HoehensteigerGames** [comment]
ok Many Many Thank you. Is there a release date available?

**Comment by safrazik** [comment]
Working on it...! Most of the core features have been implemented. There's a lot of work with documentation and testing is remaining. I don't think I can give a release date at the moment. It should probably take some time. But `v1` will be supported along the way. Thanks for your interest.

**Comment by nickbetsworth** [comment]
I am receiving the following error with your suggested approach:
```
TS2352: Conversion of type 'Vue | Element | Vue[] | Element[]' to type 'VueFileAgentComponent' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'Element[]' is missing the following properties from type 'VueFileAgentComponent': deleteFileRecord, upload, updateUpload, deleteUpload
```

I am using the component as follows:
```
<vue-file-agent 
    ref="fileUploader"
    v-model="files"
    :multiple="true">
</vue-file-agent>
```

```
(this.$refs.fileUploader as VueFileAgentComponent).upload(this.url, this.headers, this.files);
```
