### ISSUE TITLE
Not an issue. how to implement progress bar for custom upload 

### ISSUE THREAD

**Issue by drascom** [safrazik/vue-file-agent#77]
i folowed your [ advanced demo](https://github.com/safrazik/vue-file-agent/blob/master/src/demo/demo-advanced.vue) and everything is working perfectly.
but i cant figure it out how to implement upload progress bar.
can you provide any usage for custom upload function ?

please close this issue it is working now with code below.
thnak you again this wonderfull script.

```
 uploadFiles: function(customerId) {
      this.$refs.vueFileAgent.upload(
        this.uploadUrl,
        this.uploadHeaders,
        this.fileRecordsForUpload,
        function createFormData(fileData) {
          var formData = new FormData();
          formData.append("id", customerId);
          formData.append("file", fileData.file);
          return formData;
        },
uploadedEvent(eventName, event) {
      console.log("upload event başladı");
      var firstCount = Object.keys(this.fileRecordsForUpload).length;
      var files = Array.isArray(event) ? event : [event];
      for (var file of files) {
        var fileRecord = file.fileRecord;
        var index = this.fileRecords.indexOf(fileRecord);
        this.fileRecords.splice(index, 1);
        this.fileRecordsForUpload.splice(index, 1);
      }
      var LastCount = Object.keys(this.fileRecordsForUpload).length;
      if (LastCount <= 0) {
        this.$vs.notify({
          color: "success",
          title: "Uploaded",
          text: firstCount + " files were successfully uploaded",
          position: "top-right"
        });
      }
```

**Comment by safrazik** [comment]
Glad it worked for you. If anyone else is wondering how to update progress bar when using a custom uploader:

`fileRecord.progress()` - Get progress
`fileRecord.progress(30)` - Set progress to 30% (yellow bar - uploading/file is being sent)
`fileRecord.progress(99.9999)` - Set progress to almost 100% (green bar - uploaded/file sent)
`fileRecord.progress(100)` - Set progress to 100% (green dot - done/processed/completed)
