### ISSUE TITLE
Populate with Existing Files

### ISSUE THREAD

**Issue by mattkirwan** [safrazik/vue-file-agent#82]
Hi, this is an issue I can't seem to find a solution to. It's most likely my as yet limited VueJS knowledge and not a problem with vue-file-agent - but I'm not sure and any help is massively appreciated

**Describe the bug**

I'm getting the following error when navigating from a different route within my app:

```
[Vue warn]: Error in render: "TypeError: fileRecord is undefined"

found in

---> <VueFileAgent>
       <About> at resources/js/components/About.vue
         <Root>
```

I'm trying to load some default files upon mounting. This works on hard refresh of the page (all files showing with metadata etc...) however if I navigate away to a different route within my app and then back I see the above warning (files still visible though):

```
        data() {
            return {
                fruit: 'none',
                fileRecords: [],
                uploadUrl: 'http://myapi/upload',
            }
        },

        mounted() {
            axios('http://myapi/')
                .then(response => response.data)
                .then(data => {
                    data.forEach( video => {
                        this.fileRecords.push({
                            'name': video.title,
                            'url': 'https://myfilepath/' + video.filename,
                            'type': video.type,
                            'size': video.size,
                            'ext': video.extension,
                        });
                    });
                });
        }
```

**Comment by safrazik** [comment]
It is really hard to guess the issue with the information you provided. Can you give more information - error stack, any other place `fileRecord` keyword is used, etc.

---
(Maybe) not related to your issue, but you shouldn't push to the `fileRecords` array - not a good practice for Vue js in general - instead, you should assign to the array. E.g:
```javascript
            axios('http://myapi/')
                .then(response => response.data)
                .then(data => {
                    this.fileRecords = data.map( video => {
                        return {
                            'name': video.title,
                            'url': 'https://myfilepath/' + video.filename,
                            'type': video.type,
                            'size': video.size,
                            'ext': video.extension,
                        };
                    });
                });
```

**Comment by mattkirwan** [comment]
Hi @safrazik . Thank you for your swift reply. That was it! Changing it to assigning any data to `fileRecords` worked!

I have no idea as to why yet but that'll come with time in using VueJS.

I'll close this issue and would like to take this opportunity to thank you for your time - this is the first ever third party VueJS component I've ever worked with so I have no real comparison but I can say I'm enjoying working with it and so far it's far exceeding what I need to solve the problem I'm working on.

Thank you!
