### ISSUE TITLE
How can I change the SVG Icon?

### ISSUE THREAD

**Issue by just-refresh** [safrazik/vue-file-agent#84]
Hi there, 

great work. **Thanks** for taking all the time to build this awesome tool.

My Question to you:
How could i change the svg to my own?
I created and saved an SVG in ./src/assets/svg/videoUpload.svg.
So far i tried to change it with CSS

`.vue-file-agent .file-preview-new svg {
  fill: #1976d2;
  background: url(/src/assets/svg/videoUpload.svg);
}`

Is there a prop that i can use? 

Best regards

**Comment by safrazik** [comment]
Did you find the solution already? Sorry for the delay in response.

If you want to change the new file upload icon, you can use `file-preview-new` slot - [Docs for slots](https://safrazik.com/vue-file-agent/docs/#slots)

You can place any custom html. If all you want is to change the svg icon, you can use the existing html replacing only the svg as seen in the following example: IMPORTANT: Note the usage of `key="new"`. Key is required.

E.g:
```html
<VueFileAgent
  ....
>
<template v-slot:file-preview-new>
<div key="new" class="file-preview-wrapper grid-box-item grid-block file-preview-new">
  <span class="file-preview"><span style="position: absolute; top: 0px; right: 0px; bottom: 0px; left: 0px;">
    YOUR ICON HERE!
    <span class="help-text">Choose videos or drag &amp; drop here</span>
  </span></span>
</div>
</template>
</VueFileAgent>
```

**Comment by just-refresh** [comment]
Great. That works instant for me. 

Thank you!
