### ISSUE TITLE
Sortable prevents deletable

### ISSUE THREAD

**Issue by kisuka** [safrazik/vue-file-agent#87]
**Describe the bug**
When having both sortable and deletable enabled this causes an issue where the delete button is never triggered because the sortable actions are on top of the deletion button. When you attempt to delete a file it just performs a drag action.

This issue is present on the demo page as well.

**Expected behavior**
Should be able to delete a file and have sorting enabled.

**Comment by safrazik** [comment]
See #56

**Comment by kisuka** [comment]
> See #56

Got it. thanks 👍
