### ISSUE TITLE
An option to specify `crossOrigin` attribute for image and video preview

### ISSUE THREAD

**Issue by tommykamkcm** [safrazik/vue-file-agent#89]
**Is your feature request related to a problem? Please describe.**
My application uploads files to / displays images/videos from an AWS S3 bucket protected by Cloudfront signed cookies.
When the vue-file-agent loads the images/videos, there will be a javascript error in the console saying:
```
Access to image at 'https://assets.xxxxx.com/yyy.jpg' from origin 'xxxxx.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
I've tried to modify 2 lines, compile again and the error was gone.
- `src/lib/utils.ts` line 80 & 372 to `.setAttribute('crossOrigin', 'use-credentials');`

**Describe the solution you'd like**
1. Add a new Vue props `crossOrigin` (default: `anonymous`) to the component
2. Apply this attribute and its value to the <img> and <video> preview

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/1722447/94657933-bda7b700-0334-11eb-82fe-41e1f0ab9f86.png)
![image](https://user-images.githubusercontent.com/1722447/94657994-cef0c380-0334-11eb-89e3-1b84285e31c3.png)

**Comment by safrazik** [comment]
Interesting. Will have a look. Feel free to send pull requests.

**Comment by safrazik** [comment]
Now [uploadWithCredentials](https://safrazik.com/vue-file-agent/docs/#uploadwithcredentials) prop is respected for image and video previews.

```javascript
withCredentials = uploadWithCredentials // prop value
(image || video).setAttribute('crossOrigin', withCredentials ? 'use-credentials' : 'anonymous')
```
