### ISSUE TITLE
1.7.* Delete button not working without uploadUrl property

### ISSUE THREAD

**Issue by hmawla** [safrazik/vue-file-agent#94]
The delete button that removes a record doesn't work at all nor its callback when uploadUrl is null.
Test on all 1.7.* versions, 1.6.* working perfectly...

**Comment by safrazik** [comment]
See issue: #69 

Also: #59 

I’m working on v2 which will be ready in few weeks. In V2, this is handled in a better way.

**Comment by hmawla** [comment]
Thanks, and good luck, this library deserves more attention from the outside

**Comment by safrazik** [comment]
Thanks. The library has travelled to a mature state within one year - thanks to the open source community - whoever contributed and using it, including you.

File Agent v2 is not limited to Vue JS only. React and vanilla JS is supported too. The documentation is being written. So I believe it will help more people and get more attention. Thanks for your concern.
