### ISSUE TITLE
Error Message out of the Box

### ISSUE THREAD

**Issue by just-refresh** [safrazik/vue-file-agent#98]
Hey there, 

still working with your upload. 
Build two of them together with a form. Works great. 

But,
i have an other question on it: 
How can i get the reponse error out of the box?

Thanks for your help.
Best regards

**Comment by safrazik** [comment]
Sorry for the delay. I don't know if you've already solved your issue. If you have, please share your insights.

At the moment, with v1, you can do it like this:

If you want to place the errors relative to the file previews, you can customize the CSS:
```css
.vue-file-agent .file-error-wrapper {
  /* your custom css */
}
```

else if you want to display your errors in a whole new place:

```css
.vue-file-agent .file-error-wrapper {
  display: none;
}
```
```html
<div class="file-error" v-for="fileError in fileErrors">
  {{ fileError }}
</div>
```
```javascript
export default {
  data(){
    return {
      fileRecords: []
    }
  },
  computed: {
    fileErrors() {
      this.fileRecords.filter(fileRecord => !!fileRecord.error).map(fileRecord => {
        const error = fileRecord.error
        if (error.type) {
          return 'invalid file type'
        } else if (error.size) {
          return 'file is too large'
        } else if (error.upload) {
          return (fileRecord.upload && fileRecord.upload.error) ? fileRecord.upload.error : error.upload
        }
        return 'file error'
      }
    }
  }
}
```
See: https://github.com/safrazik/vue-file-agent/blob/7f7c931b51c8724c852be60a824cac7235c1dad3/src/lib/file-record.ts#L376
